apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
          - name: postgres
            image: 'postgres:latest'
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 5432
            env:

              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: postgres-configmap
                    key: POSTGRES_DB

              - name: POSTGRES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: POSTGRES_USERNAME

              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: POSTGRES_PASSWORD

            volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: postgresdata
      volumes:
          - name: postgresdata
            persistentVolumeClaim:
              claimName: postgres-volume-claim